name: financial_planner_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Memperbarui batasan SDK agar lebih standar

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  introduction_screen: ^3.1.14
  shared_preferences: ^2.2.3
  confetti: ^0.7.0 
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

# Bagian ini untuk konfigurasi Flutter
flutter:
  uses-material-design: true

  # <-- TAMBAHAN: Deklarasi folder assets -->
  # Baris ini memberitahu Flutter bahwa folder assets/icon/ ada dan bisa digunakan.
  assets:
    - assets/icon/
    - assets/animations/
    - assets/images/

# <-- TAMBAHAN: Konfigurasi untuk ikon aplikasi -->
# Konfigurasi ini akan dibaca oleh paket flutter_launcher_icons.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# <-- TAMBAHAN: Konfigurasi untuk splash screen -->
# Konfigurasi ini akan dibaca oleh paket flutter_native_splash.
flutter_native_splash:
  color: "#FFFFFF" # Warna latar belakang splash screen (putih)
  image: assets/icon/splash.png # Gambar logo di tengah
  android: true
  ios: true